### ISSUE TITLE
GitHub - Create newsletter based on repository activity

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1154] opened 2022-08-26 16:29 UTC
Create a weekly newsletter based on activity

INPUT
repo_url
email receivers

MODEL
No of issues / var
No PR/var
HTML email

OUTPUT
Send email

**Comment by SuhasBRao** [comment] 2022-10-08 06:42
Hi there, I would like to work on this issue. 
Can you give me more info on this. Like do we need a notebook that sends email when it is run or an automated newsletter that sends emails every week ata specified day.

**Comment by SuhasBRao** [comment] 2022-10-08 13:48
After a bit of searchig I found that, If we need a Jupyter notebook that sends emails at the specified time, we need to schedule notebooks using Jupyterlab Scheduler.

**Comment by jravenel** [comment] 2022-10-08 18:29
> After a bit of searchig I found that, If we need a Jupyter notebook that sends emails at the specified time, we need to schedule notebooks using Jupyterlab Scheduler.

#@SuhasBRao It's seems like you did not check Naas Scheduler and notification in docs.naas.ai we specifically fixed that 🤗

**Comment by SuhasBRao** [comment] 2022-10-09 02:42
Oh I did not know about that 😅. I'll look into it.

**Comment by SuhasBRao** [comment] 2022-10-09 14:02
Thanks @jravenel, I read the documentation now I am able to send the email without any issues. Here's a sample mail that I sent.

![Screenshot from 2022-10-09 19-26-59](https://user-images.githubusercontent.com/65769327/194761123-01a59f95-0a56-4652-9158-fb4c74bc6e96.png)




But I feel we need more content based on Issues/PR activity. Here only 5 recent issues and PRs are shown. Do you have any suggestions?

**Comment by jravenel** [comment] 2022-10-11 00:31
My feedback: 
- no need for logo 
- need to pass the number of days in the past as input
- text: ""
Hello there, 
Here is what happened over the past 7 days on awesome-notebooks: 

**Issues created = 12**
[Name of issue 1]() -> plain text name with href  
Name of issue 2

**Issues closed = 4**
[Name of issue 1](), closed by [PR #123]() by @SuhasBRao 
Name of issue 2, closed by PR #123 by @FlorentLvr  

[>> Check out the latest issues activity on GitHub](https://github.com/jupyter-naas/awesome-notebooks/issues?q=is%3Aissue+sort%3Aupdated-desc+)

Cheers
""

**Comment by SuhasBRao** [comment] 2022-10-11 04:41
Nice, I will modify it accordingly

**Comment by SuhasBRao** [comment] 2022-10-12 07:43
Here is a snapshot of the updated email content, @jravenel let me know what you think.

![Screenshot from 2022-10-12 13-10-53](https://user-images.githubusercontent.com/65769327/195280873-f6df745e-1c15-4a2a-8885-07cb765112e5.png)

If it's fine I'll create a PR.

**Comment by SuhasBRao** [comment] 2022-10-13 01:38
Sure thing I will modify, I didn't get the first point though. "no need to add a sentence after the title". 
Do you want me to remove sentences like "Here are few of them,' is that right?

**Comment by jravenel** [comment] 2022-10-13 09:24
@SuhasBRao yes you got it, no need to have the "recent ones" we need all of them on the time-frame requested (x days)

**Comment by SuhasBRao** [comment] 2022-10-13 12:15
Modified the newsletter as per needs
[Newsletter.webm](https://user-images.githubusercontent.com/65769327/195593101-4dbdfacd-ffea-443e-954f-6a1b63630169.webm)

@jravenel and @FlorentLvr  what do you think?

**Comment by jravenel** [comment] 2022-10-13 13:54
My feedback : 

→ here we can remove the "-" in "-PR"? #display
<img width="969" alt="Screenshot 2022-10-13 at 15 10 09" src="https://user-images.githubusercontent.com/21052349/195614975-2075f2dc-d488-48ef-bdd8-b9c264bf0528.png">

→ here, can we put spaces between number " - " and PR #display 
<img width="969" alt="Screenshot 2022-10-13 at 15 10 09" src="https://user-images.githubusercontent.com/21052349/195615345-0234c2fb-d11c-41ad-8865-d95e2f086ff9.png">

→ here there is a problem in the data for example first ligne should be [BigFunctions - Get sentiment score#1240](https://github.com/jupyter-naas/awesome-notebooks/issues/1240)
<img width="1209" alt="Screenshot 2022-10-13 at 15 51 54" src="https://user-images.githubusercontent.com/21052349/195615857-e575c5b5-7169-4fae-ac82-80d10c4b5fad.png">

**Comment by SuhasBRao** [comment] 2022-10-13 14:17
@jravenel I can modify Issue_open and Issue_closed accordingly but for PRs I don't have idea to retrieve the corresponding issues, right now I have written a function to get open PRs which gets "ref" field from [here](https://api.github.com/repos/jupyter-naas/awesome-notebooks/pulls?state=open&per_page=1).

like this,
**df.loc[idx, 'issue_ref_title'] = r.get('head').get('ref')**

Can you help me with this, I need to get the issue name to which the PR is linked. the display part I can modify

**Comment by SuhasBRao** [comment] 2022-10-13 14:45
I can think of one solution,  we can modify that string itself and display it in a proper format.
And do you have an idea on how we can link that issue name to its respective issue on github.

**Comment by SuhasBRao** [comment] 2022-10-14 10:20
Hey @jravenel, I am facing an issue, while accessing **issue** linked to a PR, the problem is that GitHub recognizes PR as a separate issue, so I can only retrieve **ref** object from a [PR API here](https://api.github.com/repos/jupyter-naas/awesome-notebooks/pulls/1252) which gives the name of issue ( in a different format as in the above comment ). Whereas the original issue linked to it is [Issue name](https://github.com/jupyter-naas/awesome-notebooks/issues/1177).

The only option I see is to just list the name of the PR itself rather than linking it to the issue, If you have any ideas do let me know.

**Comment by SuhasBRao** [comment] 2022-10-14 10:23
Here's a snapshot of latest content as of now,
![Screenshot from 2022-10-14 15-50-56](https://user-images.githubusercontent.com/65769327/195824091-9ab7879c-1ff5-48fd-85b7-705fd6d02217.png)

You can see that issues created also includes PRs along with the Open issues,  this is because github treated open PRs as open issues.

**Comment by jravenel** [comment] 2022-10-29 17:09
Reopenning it because of data quality issue @FlorentLvr @SuhasBRao I've done a video to explain: https://www.loom.com/share/c6fc45384fed4e7e86303f2cb4c6f38f

Any thoughts on how we can fix it?

**Comment by jravenel** [comment] 2022-10-29 17:17
@SuhasBRao I've create a new branch and started by renaming title for better clarity. 
I'm happy to do a workshop on this with you because it's something that a lot of open source projects could use !

**Comment by SuhasBRao** [comment] 2022-10-30 02:10
> Reopenning it because of data quality issue @FlorentLvr @SuhasBRao I've done a video to explain: https://www.loom.com/share/c6fc45384fed4e7e86303f2cb4c6f38f
> 
> Any thoughts on how we can fix it?

Thank you @jravenel for taking time and reviewing this issue, 

I see the problem is because **GitHub treats Open PRs also as issues**. So I think we have to use different API calls while fetching data. I will look into it and revert back if I make any progress.

**Comment by SuhasBRao** [comment] 2022-10-30 06:28
I merged the PR you created to the master branch, For some reason, I was not able to access that branch on Naas cloud. I will create a new branch and work on it.

**Comment by SuhasBRao** [comment] 2022-10-30 07:57
@jravenel I made the necessary changes it seems to work fine, I have triggered an email to jeremy@naas.ai, so that you can test it out easily.

**Comment by SuhasBRao** [comment] 2022-11-02 07:19
Re-opening this issue to review the Updated file on new branch. @jravenel please review  the new PR from a different branch.

**Closed** 2022-11-29 08:24 UTC
Labels: good first issue, hacktoberfest
